# Generated by Django 4.2.1 on 2024-03-21 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_id_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=37, primary_key=True, serialize=False),
        ),
    ]
